name: Validate Packer template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

permissions:
  contents: write

jobs:
  validate:
    name: Validate Packer template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Validate
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
          # Make sure that validate does not fail due to unset variables
          PKR_VAR_proxmox_api_url: 'https://proxmox.example.com:8006/api2/json'
          PKR_VAR_proxmox_api_token_id: 'id'
          PKR_VAR_proxmox_api_token_secret: 'secret'
        run: |
          packer init -force -upgrade .

          echo "### 📦 Packer Validation Results" >> $GITHUB_STEP_SUMMARY
          
          set +e
          OUTPUT=$(packer validate . 2>&1)
          EXIT_CODE=$?
          set -e

          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ **Syntax Valid**" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Syntax Invalid**" >> $GITHUB_STEP_SUMMARY
            echo '```term' >> $GITHUB_STEP_SUMMARY
            echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
